import type { Lesson } from './lessons'

/** 12 ta ingliz zamoni — har biri to‘liq ko‘nikmalar bilan */
export const TENSE_LESSONS: Lesson[] = [
  {
    id: 'present-simple',
    num: 8,
    level: 'boshlangich',
    topic: 'zamon',
    title: 'Present Simple',
    summary: 'Odat, fakt, jadval — I work / she works.',
    minutes: 25,
    tip: 'He/She/It uchun fe’lga -s/-es. So‘roq/inkor: do / does.',
    formula: '+ V1 / he-she-it V1+s  |  − don’t/doesn’t + V1  |  ? Do/Does + S + V1?',
    signals: ['every day', 'always', 'usually', 'often', 'sometimes', 'never', 'on Mondays'],
    words: [
      { en: 'always', uz: 'doim' },
      { en: 'usually', uz: 'odatda' },
      { en: 'often', uz: 'tez-tez' },
      { en: 'sometimes', uz: 'ba’zan' },
      { en: 'never', uz: 'hech qachon' },
      { en: 'every day', uz: 'har kuni' },
      { en: 'work / works', uz: 'ishlamoq' },
      { en: 'do / does', uz: 'yordamchi fe’l' },
      { en: "don't / doesn't", uz: 'inkor' },
      { en: 'fact', uz: 'fakt' },
    ],
    phrases: [
      { en: 'I work every day.', uz: 'Men har kuni ishlayman.' },
      { en: 'She works in a bank.', uz: 'U bankda ishlaydi.' },
      { en: 'Water boils at 100°C.', uz: 'Suv 100°C da qaynaydi.' },
      { en: 'Do you speak English?', uz: 'Inglizcha gapirasizmi?' },
      { en: "He doesn't like coffee.", uz: 'U qahva yoqtirmaydi.' },
      { en: 'The train leaves at 9.', uz: 'Poyezd soat 9 da jo‘naydi.' },
    ],
    quiz: [
      {
        prompt: 'To‘g‘ri shakl:',
        options: ['She work', 'She works', 'She working', 'She is work'],
        answer: 1,
        hint: 'he/she/it → -s',
      },
      {
        prompt: 'Inkor (he):',
        options: ["He don't like tea", "He doesn't like tea", 'He not likes tea', 'He no like tea'],
        answer: 1,
      },
      {
        prompt: 'So‘roq:',
        options: ['Does you work?', 'Do she work?', 'Do you work?', 'Are you work?'],
        answer: 2,
      },
      {
        prompt: 'Qachon Present Simple?',
        options: ['Hozir bo‘layotgan ish', 'Odat / fakt', 'Kecha bitgan ish', 'Ertaga reja (aniq)'],
        answer: 1,
      },
      {
        prompt: '“always” qaysi zamon bilan ko‘p?',
        options: ['Present Continuous', 'Present Simple', 'Past Perfect', 'Future Perfect'],
        answer: 1,
      },
    ],
    reading: {
      title: 'My routine',
      text: 'I usually get up at seven. My sister works in a hospital. She doesn’t drink coffee. Do you wake up early? Water freezes at 0°C. The bus leaves every morning at eight.',
      questions: [
        {
          prompt: 'Opa qayerda ishlaydi?',
          options: ['Maktabda', 'Kasalxonada', 'Bankda', 'Do‘konda'],
          answer: 1,
        },
        {
          prompt: 'Qaysi gap fakt?',
          options: [
            'Water freezes at 0°C',
            'I am getting up now',
            'She was working',
            'I will freeze',
          ],
          answer: 0,
        },
        {
          prompt: 'Avtobus qachon jo‘naydi?',
          options: ['Kechqurun', 'Har ertalab soat 8', 'Faqat yakshanba', 'Hech qachon'],
          answer: 1,
        },
      ],
    },
    writing: [
      { promptUz: '“U bankda ishlaydi.” (she)', answer: 'She works in a bank.' },
      { promptUz: '“Inglizcha gapirasizmi?”', answer: 'Do you speak English?' },
      {
        promptUz: '“U qahva yoqtirmaydi.” (he)',
        answer: "He doesn't like coffee.",
        accept: ['He does not like coffee.'],
      },
      { promptUz: '“Men har kuni ishlayman.”', answer: 'I work every day.' },
    ],
    listening: [
      {
        audioText: 'She works in a bank',
        options: ['She work in a bank', 'She works in a bank', 'She working in a bank', 'She worked in a bank'],
        answer: 1,
      },
      {
        audioText: "He doesn't like coffee",
        options: [
          "He don't like coffee",
          "He doesn't like coffee",
          'He not like coffee',
          "He doesn't likes coffee",
        ],
        answer: 1,
      },
      {
        audioText: 'Do you speak English?',
        options: ['Do you speak English?', 'Does you speak English?', 'Are you speak English?', 'Did you speak English?'],
        answer: 0,
      },
      {
        audioText: 'I usually get up at seven',
        options: [
          'I usually get up at seven',
          'I usual get up at seven',
          'I am usually get up at seven',
          'I usually got up at seven',
        ],
        answer: 0,
      },
    ],
    pronounce: [
      { text: 'works', tip: 'works — oxirida qattiq s' },
      { text: 'does', tip: 'daz' },
      { text: "doesn't", tip: 'DUZ-nt' },
      { text: 'usually', tip: 'YOO-zhu-u-li' },
      { text: 'Do you speak English?', tip: 'Do you — birga, yumshoq' },
    ],
  },
  {
    id: 'present-continuous',
    num: 9,
    level: 'boshlangich',
    topic: 'zamon',
    title: 'Present Continuous',
    summary: 'Hozir bo‘layotgan ish — I am working.',
    minutes: 25,
    tip: 'am/is/are + V-ing. Hozir / vaqtinchalik holat.',
    formula: '+ am/is/are + V-ing  |  − am/is/are + not + V-ing  |  ? Am/Is/Are + S + V-ing?',
    signals: ['now', 'right now', 'at the moment', 'today', 'Look!', 'Listen!'],
    words: [
      { en: 'now', uz: 'hozir' },
      { en: 'at the moment', uz: 'shu paytda' },
      { en: 'right now', uz: 'hozirning o‘zida' },
      { en: 'am / is / are', uz: 'yordamchi' },
      { en: 'working', uz: 'ishlayotgan' },
      { en: 'studying', uz: 'o‘qiyotgan' },
      { en: 'waiting', uz: 'kutayotgan' },
      { en: "isn't / aren't", uz: 'inkor' },
      { en: 'temporary', uz: 'vaqtinchalik' },
      { en: 'Look!', uz: 'Qara!' },
    ],
    phrases: [
      { en: 'I am learning English now.', uz: 'Hozir ingliz tilini o‘rganayapman.' },
      { en: 'She is cooking dinner.', uz: 'U kechki ovqat pishiryapti.' },
      { en: 'They are waiting for the bus.', uz: 'Ular avtobus kutishyapti.' },
      { en: 'Are you watching TV?', uz: 'TV ko‘ryapsizmi?' },
      { en: "He isn't sleeping.", uz: 'U uxlamayapti.' },
      { en: 'Look! It is raining.', uz: 'Qara! Yomg‘ir yog‘yapti.' },
    ],
    quiz: [
      {
        prompt: 'To‘g‘ri:',
        options: ['She cooking', 'She is cook', 'She is cooking', 'She cooks now (yagona to‘g‘ri emas)'],
        answer: 2,
      },
      {
        prompt: 'So‘roq:',
        options: ['Do you watching?', 'Are you watching?', 'Is you watching?', 'You are watching?'],
        answer: 1,
      },
      {
        prompt: 'Inkor:',
        options: ["He don't sleeping", "He isn't sleeping", 'He not sleep', "He doesn't sleeping"],
        answer: 1,
      },
      {
        prompt: 'Qachon Present Continuous?',
        options: ['Har doimgi odat', 'Hozir bo‘layotgan ish', 'Kecha bitgan', 'Ertaga umumiy bashorat'],
        answer: 1,
      },
      {
        prompt: '“Look!” dan keyin odatda:',
        options: ['Present Simple', 'Present Continuous', 'Past Perfect', 'Future Perfect'],
        answer: 1,
      },
    ],
    reading: {
      title: 'Right now',
      text: 'I am sitting in a café. My friend is calling a taxi. People are talking loudly. Look! It is raining outside. We are not working today; we are resting.',
      questions: [
        {
          prompt: 'Men qayerdaman?',
          options: ['Uyda', 'Kafeda', 'Maktabda', 'Avtobusda'],
          answer: 1,
        },
        {
          prompt: 'Tashqarida nima bo‘lyapti?',
          options: ['Qor', 'Yomg‘ir', 'Quyosh', 'Shamol yo‘q'],
          answer: 1,
        },
        {
          prompt: 'Bugun ishlashyaptimi?',
          options: ['Ha', 'Yo‘q, dam olyapti', 'Faqat ertalab', 'Bilmaymiz'],
          answer: 1,
        },
      ],
    },
    writing: [
      { promptUz: '“Hozir o‘rganayapman.” (I + learn)', answer: 'I am learning English now.', accept: ['I am learning now.'] },
      { promptUz: '“U uxlamayapti.” (he)', answer: "He isn't sleeping.", accept: ['He is not sleeping.'] },
      { promptUz: '“TV ko‘ryapsizmi?”', answer: 'Are you watching TV?' },
      { promptUz: '“Yomg‘ir yog‘yapti.”', answer: 'It is raining.', accept: ["It's raining."] },
    ],
    listening: [
      {
        audioText: 'I am learning English now',
        options: [
          'I am learning English now',
          'I learning English now',
          'I learn English now',
          'I am learn English now',
        ],
        answer: 0,
      },
      {
        audioText: "He isn't sleeping",
        options: ["He isn't sleeping", "He doesn't sleeping", 'He not sleeping', "He isn't sleep"],
        answer: 0,
      },
      {
        audioText: 'Are you watching TV?',
        options: ['Are you watching TV?', 'Do you watching TV?', 'Is you watching TV?', 'Are you watch TV?'],
        answer: 0,
      },
      {
        audioText: 'Look! It is raining',
        options: ['Look! It is raining', 'Look! It rains', 'Look! It raining', 'Look! It is rain'],
        answer: 0,
      },
    ],
    pronounce: [
      { text: 'working', tip: 'WER-king' },
      { text: 'sitting', tip: 'ikki t — SI-ting' },
      { text: "isn't", tip: 'IZ-nt' },
      { text: 'at the moment', tip: 'the — yumshoq' },
      { text: 'Are you watching TV?', tip: 'watching — “ch”' },
    ],
  },
  {
    id: 'present-perfect',
    num: 10,
    level: 'ortacha',
    topic: 'zamon',
    title: 'Present Perfect',
    summary: 'O‘tgan tajriba / natija — I have done.',
    minutes: 28,
    tip: 'have/has + V3. Vaqt aniq aytilmasa; ever/never/just/already/yet.',
    formula: '+ have/has + V3  |  − haven’t/hasn’t + V3  |  ? Have/Has + S + V3?',
    signals: ['ever', 'never', 'just', 'already', 'yet', 'since', 'for', 'recently'],
    words: [
      { en: 'have / has', uz: 'yordamchi' },
      { en: 'done (V3)', uz: 'qilgan' },
      { en: 'been', uz: 'bo‘lgan' },
      { en: 'gone', uz: 'ketgan' },
      { en: 'ever', uz: 'hech (so‘roqda)' },
      { en: 'never', uz: 'hech qachon' },
      { en: 'just', uz: 'hozirgina' },
      { en: 'already', uz: 'allaqachon' },
      { en: 'yet', uz: 'hali (inkor/so‘roq)' },
      { en: 'since / for', uz: '…dan beri / …davomida' },
    ],
    phrases: [
      { en: 'I have finished my homework.', uz: 'Uy vazifamni tugatdim (natija hozir).' },
      { en: 'She has never been to London.', uz: 'U hech qachon Londonda bo‘lmagan.' },
      { en: 'Have you ever eaten plov?', uz: 'Hech palov yeganmisiz?' },
      { en: 'He has just left.', uz: 'U hozirgina ketdi.' },
      { en: "We haven't started yet.", uz: 'Biz hali boshlamadik.' },
      { en: 'I have lived here for five years.', uz: 'Bu yerda 5 yildan beri yashayman.' },
    ],
    quiz: [
      {
        prompt: 'To‘g‘ri:',
        options: ['She have gone', 'She has go', 'She has gone', 'She is gone yesterday'],
        answer: 2,
      },
      {
        prompt: '“yet” odatda qayerda?',
        options: ['Faqat + gapda', 'Inkor va so‘roqda', 'Faqat Past Simple', 'Faqat Future'],
        answer: 1,
      },
      {
        prompt: 'since vs for:',
        options: [
          'since = davomiylik, for = boshlanish nuqtasi',
          'since = boshlanish nuqtasi, for = davomiylik',
          'ikkalasi bir xil',
          'since faqat kelajak',
        ],
        answer: 1,
      },
      {
        prompt: 'Qachon Present Perfect?',
        options: [
          'Aniq kecha soat 5 (faqat)',
          'Tajriba / hozirgi natija',
          'Hozir aynan qilyapman',
          'Ertaga aniq uchrashuv',
        ],
        answer: 1,
      },
      {
        prompt: 'So‘roq:',
        options: ['Have you ever been…?', 'Did you ever been…?', 'Has you ever been…?', 'Do you ever been…?'],
        answer: 0,
      },
    ],
    reading: {
      title: 'Life so far',
      text: 'I have visited Samarkand twice. My brother has never flown. Have you finished? Yes, I have just finished. We haven’t eaten yet. She has lived in Tashkent since 2019.',
      questions: [
        {
          prompt: 'Samarqandga necha marta?',
          options: ['1', '2', '3', '0'],
          answer: 1,
        },
        {
          prompt: 'Aka/uka uchganmi?',
          options: ['Ha', 'Yo‘q, hech qachon', 'Faqat bir marta', 'Har kuni'],
          answer: 1,
        },
        {
          prompt: 'U qachondan beri Toshkentda?',
          options: ['2019 dan', '2025 dan', 'Kechadan', 'Ertadan'],
          answer: 0,
        },
      ],
    },
    writing: [
      { promptUz: '“Uy vazifamni tugatdim.” (I + finish)', answer: 'I have finished my homework.' },
      {
        promptUz: '“U hech qachon Londonda bo‘lmagan.” (she)',
        answer: 'She has never been to London.',
      },
      { promptUz: '“Hali boshlamadik.” (we)', answer: "We haven't started yet.", accept: ['We have not started yet.'] },
      {
        promptUz: '“Bu yerda 5 yildan beri yashayman.”',
        answer: 'I have lived here for five years.',
      },
    ],
    listening: [
      {
        audioText: 'She has never been to London',
        options: [
          'She has never been to London',
          'She have never been to London',
          'She never was to London',
          'She has never be to London',
        ],
        answer: 0,
      },
      {
        audioText: 'Have you ever eaten plov?',
        options: [
          'Have you ever eaten plov?',
          'Did you ever eaten plov?',
          'Has you ever eaten plov?',
          'Have you ever ate plov?',
        ],
        answer: 0,
      },
      {
        audioText: 'He has just left',
        options: ['He has just left', 'He have just left', 'He just leave', 'He has just leaved'],
        answer: 0,
      },
      {
        audioText: "We haven't started yet",
        options: [
          "We haven't started yet",
          "We didn't started yet",
          "We hasn't started yet",
          "We haven't start yet",
        ],
        answer: 0,
      },
    ],
    pronounce: [
      { text: 'have', tip: 'hav / əv (zaif)' },
      { text: 'has', tip: 'haz' },
      { text: 'finished', tip: '-ed = /t/' },
      { text: 'already', tip: 'ol-RE-di' },
      { text: 'Have you ever…?', tip: 'ever — E-ver' },
    ],
  },
  {
    id: 'present-perfect-continuous',
    num: 11,
    level: 'ortacha',
    topic: 'zamon',
    title: 'Present Perfect Continuous',
    summary: 'Boshlanib hali davom — I have been working.',
    minutes: 28,
    tip: 'have/has + been + V-ing. Davomiylik / charchoq urg‘usi.',
    formula: '+ have/has + been + V-ing  |  − haven’t/hasn’t + been + V-ing  |  ? Have/Has + S + been + V-ing?',
    signals: ['for', 'since', 'all day', 'lately', 'recently', 'How long…?'],
    words: [
      { en: 'been', uz: 'bo‘lgan (yordamchi)' },
      { en: 'working', uz: 'ishlab kelayotgan' },
      { en: 'waiting', uz: 'kutib turgan' },
      { en: 'How long…?', uz: 'Qancha vaqtdan beri…?' },
      { en: 'all day', uz: 'kun bo‘yi' },
      { en: 'lately', uz: 'so‘nggi paytlarda' },
      { en: 'tired', uz: 'charchagan' },
      { en: 'since morning', uz: 'ertadan beri' },
      { en: 'for two hours', uz: 'ikki soatdan beri' },
      { en: 'still', uz: 'hali ham' },
    ],
    phrases: [
      { en: 'I have been studying for two hours.', uz: 'Ikki soatdan beri o‘qiyapman.' },
      { en: 'She has been waiting since morning.', uz: 'U ertadan beri kutayapti.' },
      { en: 'How long have you been learning English?', uz: 'Ingliz tilini qancha vaqtdan beri o‘rganasiz?' },
      { en: 'It has been raining all day.', uz: 'Kun bo‘yi yomg‘ir yog‘yapti.' },
      { en: "They haven't been sleeping well lately.", uz: 'Ular so‘nggi paytlarda yaxshi uxlamayapti.' },
      { en: 'I am tired because I have been running.', uz: 'Charchadim, chunki yugurib keldim.' },
    ],
    quiz: [
      {
        prompt: 'To‘g‘ri:',
        options: [
          'I have been work',
          'I have been working',
          'I has been working',
          'I am been working',
        ],
        answer: 1,
      },
      {
        prompt: 'Present Perfect dan farqi ko‘pincha:',
        options: [
          'Faqat kelajak',
          'Davomiylik / jarayon urg‘usi',
          'Faqat faktlar',
          'Faqat kecha',
        ],
        answer: 1,
      },
      {
        prompt: 'So‘roq:',
        options: [
          'How long you have been…?',
          'How long have you been…?',
          'How long are you been…?',
          'How long did you been…?',
        ],
        answer: 1,
      },
      {
        prompt: '“all day” bilan ko‘p:',
        options: ['Past Simple', 'Present Perfect Continuous', 'Future Simple', 'Past Perfect'],
        answer: 1,
      },
      {
        prompt: 'Inkor:',
        options: [
          "I haven't been sleeping well",
          "I haven't been sleep well",
          "I didn't been sleeping",
          'I am not been sleeping',
        ],
        answer: 0,
      },
    ],
    reading: {
      title: 'All morning',
      text: 'I have been cleaning since 8 a.m. My sister has been talking on the phone for an hour. How long have you been waiting? It has been snowing all morning. We haven’t been going out much lately.',
      questions: [
        {
          prompt: 'Men soat nechidan beri tozalayapman?',
          options: ['7', '8', '9', '10'],
          answer: 1,
        },
        {
          prompt: 'Opa qancha vaqtdan beri gaplashyapti?',
          options: ['10 daqiqa', '1 soat', '2 soat', 'Kun bo‘yi'],
          answer: 1,
        },
        {
          prompt: 'So‘nggi paytlarda ko‘p chiqyaptimi?',
          options: ['Ha', 'Yo‘q, unchalik emas', 'Har kuni', 'Faqat kechasi'],
          answer: 1,
        },
      ],
    },
    writing: [
      {
        promptUz: '“Ikki soatdan beri o‘qiyapman.”',
        answer: 'I have been studying for two hours.',
      },
      {
        promptUz: '“Qancha vaqtdan beri o‘rganasiz?” (English)',
        answer: 'How long have you been learning English?',
      },
      {
        promptUz: '“Kun bo‘yi yomg‘ir yog‘yapti.”',
        answer: 'It has been raining all day.',
      },
      {
        promptUz: '“U ertadan beri kutayapti.” (she)',
        answer: 'She has been waiting since morning.',
      },
    ],
    listening: [
      {
        audioText: 'I have been studying for two hours',
        options: [
          'I have been studying for two hours',
          'I have studying for two hours',
          'I have been study for two hours',
          'I am been studying for two hours',
        ],
        answer: 0,
      },
      {
        audioText: 'How long have you been learning English?',
        options: [
          'How long have you been learning English?',
          'How long are you learning English?',
          'How long you have been learning English?',
          'How long have you learning English?',
        ],
        answer: 0,
      },
      {
        audioText: 'It has been raining all day',
        options: [
          'It has been raining all day',
          'It has raining all day',
          'It have been raining all day',
          'It is been raining all day',
        ],
        answer: 0,
      },
      {
        audioText: 'She has been waiting since morning',
        options: [
          'She has been waiting since morning',
          'She have been waiting since morning',
          'She has waiting since morning',
          'She has been wait since morning',
        ],
        answer: 0,
      },
    ],
    pronounce: [
      { text: 'been', tip: 'bin' },
      { text: 'been working', tip: 'been + working birga' },
      { text: 'How long…?', tip: 'long — uzun o' },
      { text: 'lately', tip: 'LAYT-li' },
      { text: 'for two hours', tip: 'for — zaif' },
    ],
  },
  {
    id: 'past-simple',
    num: 12,
    level: 'boshlangich',
    topic: 'zamon',
    title: 'Past Simple',
    summary: 'O‘tgan bitgan ish — I worked / went.',
    minutes: 26,
    tip: 'V2 yoki -ed. So‘roq/inkor: did + V1. Aniq vaqt: yesterday, ago…',
    formula: '+ V2 / V-ed  |  − didn’t + V1  |  ? Did + S + V1?',
    signals: ['yesterday', 'last week', 'ago', 'in 2020', 'when I was a child'],
    words: [
      { en: 'yesterday', uz: 'kecha' },
      { en: 'last week', uz: 'o‘tgan hafta' },
      { en: 'ago', uz: '…oldin' },
      { en: 'worked', uz: 'ishladi' },
      { en: 'went', uz: 'bordi' },
      { en: 'saw', uz: 'ko‘rdi' },
      { en: 'did', uz: 'yordamchi / qildi' },
      { en: "didn't", uz: 'inkor' },
      { en: 'finished', uz: 'tugatdi' },
      { en: 'was / were', uz: 'edi' },
    ],
    phrases: [
      { en: 'I visited my grandma yesterday.', uz: 'Kecha buvimnikiga bordim.' },
      { en: 'She went to school by bus.', uz: 'U maktabga avtobusda bordi.' },
      { en: 'Did you watch the film?', uz: 'Filmni ko‘rdingizmi?' },
      { en: "We didn't go out last night.", uz: 'Kecha tashqariga chiqmadik.' },
      { en: 'He was tired after work.', uz: 'Ishdan keyin u charchagan edi.' },
      { en: 'They lived here in 2018.', uz: 'Ular 2018-da shu yerda yashagan.' },
    ],
    quiz: [
      {
        prompt: 'To‘g‘ri:',
        options: ['She go yesterday', 'She went yesterday', 'She gone yesterday', 'She goes yesterday'],
        answer: 1,
      },
      {
        prompt: 'So‘roq:',
        options: ['Did you went?', 'Did you go?', 'Do you went?', 'Were you go?'],
        answer: 1,
      },
      {
        prompt: 'Inkor:',
        options: ["I didn't went", "I didn't go", "I don't went", 'I not went'],
        answer: 1,
      },
      {
        prompt: 'Qachon Past Simple?',
        options: ['Hozirgi odat', 'O‘tgan bitgan vaqt', 'Hozirgi natija (aniq vaqtsiz)', 'Ertaga'],
        answer: 1,
      },
      {
        prompt: '“ago” bilan:',
        options: ['Present Perfect', 'Past Simple', 'Present Continuous', 'Future Perfect'],
        answer: 1,
      },
    ],
    reading: {
      title: 'Last weekend',
      text: 'Last Saturday I cleaned the house. My friends visited me. We watched a film and ate plov. Did it rain? No, it didn’t. On Sunday I stayed home and rested.',
      questions: [
        {
          prompt: 'Shanba kuni nima qildim?',
          options: ['Sayohat', 'Uyni tozalash', 'Ishlash', 'Maktab'],
          answer: 1,
        },
        {
          prompt: 'Yomg‘ir yog‘dimi?',
          options: ['Ha', 'Yo‘q', 'Qor yog‘di', 'Bilmaymiz'],
          answer: 1,
        },
        {
          prompt: 'Yakshanba kuni:',
          options: ['Safarga ketdi', 'Uyda dam oldi', 'Ishga bordi', 'Imtihon topshirdi'],
          answer: 1,
        },
      ],
    },
    writing: [
      { promptUz: '“Kecha buvimnikiga bordim.”', answer: 'I visited my grandma yesterday.' },
      { promptUz: '“Filmni ko‘rdingizmi?”', answer: 'Did you watch the film?' },
      {
        promptUz: '“Kecha chiqmadik.” (we)',
        answer: "We didn't go out last night.",
        accept: ['We did not go out last night.'],
      },
      { promptUz: '“U maktabga avtobusda bordi.” (she)', answer: 'She went to school by bus.' },
    ],
    listening: [
      {
        audioText: 'I visited my grandma yesterday',
        options: [
          'I visited my grandma yesterday',
          'I visit my grandma yesterday',
          'I have visited my grandma yesterday',
          'I visiting my grandma yesterday',
        ],
        answer: 0,
      },
      {
        audioText: 'Did you watch the film?',
        options: ['Did you watch the film?', 'Did you watched the film?', 'Do you watch the film?', 'Have you watch the film?'],
        answer: 0,
      },
      {
        audioText: "We didn't go out last night",
        options: [
          "We didn't go out last night",
          "We didn't went out last night",
          "We don't go out last night",
          'We not go out last night',
        ],
        answer: 0,
      },
      {
        audioText: 'She went to school by bus',
        options: [
          'She went to school by bus',
          'She go to school by bus',
          'She gone to school by bus',
          'She has went to school by bus',
        ],
        answer: 0,
      },
    ],
    pronounce: [
      { text: 'worked', tip: '-ed = /t/' },
      { text: 'visited', tip: '-ed = /ɪd/' },
      { text: 'played', tip: '-ed = /d/' },
      { text: 'yesterday', tip: 'YES-ter-day' },
      { text: "didn't", tip: 'DID-nt' },
    ],
  },
  {
    id: 'past-continuous',
    num: 13,
    level: 'ortacha',
    topic: 'zamon',
    title: 'Past Continuous',
    summary: 'O‘tmishda davom — I was working when…',
    minutes: 26,
    tip: 'was/were + V-ing. Fon / bir vaqtda ikki ish / when + Past Simple.',
    formula: '+ was/were + V-ing  |  − wasn’t/weren’t + V-ing  |  ? Was/Were + S + V-ing?',
    signals: ['while', 'when', 'as', 'at 5 pm yesterday', 'all evening'],
    words: [
      { en: 'was / were', uz: 'edi (yordamchi)' },
      { en: 'while', uz: '…paytida' },
      { en: 'when', uz: 'qachon / …ganda' },
      { en: 'suddenly', uz: 'to‘satdan' },
      { en: 'at that time', uz: 'o‘sha paytda' },
      { en: 'reading', uz: 'o‘qiyotgan edi' },
      { en: 'driving', uz: 'haydayotgan edi' },
      { en: "wasn't / weren't", uz: 'inkor' },
      { en: 'background', uz: 'fon (voqea)' },
      { en: 'interrupted', uz: 'uzildi' },
    ],
    phrases: [
      { en: 'I was cooking when he called.', uz: 'U qo‘ng‘iroq qilganda men ovqat pishirayotgan edim.' },
      { en: 'They were playing football at 5.', uz: 'Ular soat 5 da futbol o‘ynayotgan edi.' },
      { en: 'Was she sleeping?', uz: 'U uxlayotgan midimi?' },
      { en: "We weren't listening carefully.", uz: 'Biz diqqat bilan tinglamayotgan edik.' },
      { en: 'While I was walking, it started to rain.', uz: 'Yurib ketayotganimda yomg‘ir boshladi.' },
      { en: 'He was driving home all evening.', uz: 'U butun kechqurun uyga haydab ketayotgan edi.' },
    ],
    quiz: [
      {
        prompt: 'To‘g‘ri:',
        options: ['I was cook', 'I was cooking', 'I were cooking', 'I cooking'],
        answer: 1,
      },
      {
        prompt: 'when + odatda:',
        options: [
          'Past Continuous (qisqa ish) + Past Simple (fon)',
          'Past Simple (qisqa) + Past Continuous (fon)',
          'Faqat Present',
          'Faqat Future',
        ],
        answer: 1,
      },
      {
        prompt: 'So‘roq:',
        options: ['Was she sleeping?', 'Did she sleeping?', 'Were she sleeping?', 'Is she slept?'],
        answer: 0,
      },
      {
        prompt: 'Inkor (we):',
        options: [
          "We wasn't listening",
          "We weren't listening",
          "We didn't listening",
          'We not were listening',
        ],
        answer: 1,
      },
      {
        prompt: '“while” bilan ko‘p:',
        options: ['Past Continuous', 'Present Perfect', 'Future Simple', 'Past Perfect Continuous (faqat)'],
        answer: 0,
      },
    ],
    reading: {
      title: 'Yesterday evening',
      text: 'At 7 pm I was having dinner. My phone rang while I was eating. My brother was watching TV and my mother was reading. We weren’t talking. Suddenly the lights went out.',
      questions: [
        {
          prompt: 'Soat 7 da nima qilayotgan edim?',
          options: ['Uxlash', 'Kechki ovqat', 'Yugurish', 'Dars'],
          answer: 1,
        },
        {
          prompt: 'Telefon qachon jiringladi?',
          options: ['Yotganda', 'Ovqtlanayotganda', 'Maktabda', 'Ertaga'],
          answer: 1,
        },
        {
          prompt: 'To‘satdan nima bo‘ldi?',
          options: ['Mehmon keldi', 'Chiroq o‘chdi', 'Yomg‘ir', 'Film tugadi'],
          answer: 1,
        },
      ],
    },
    writing: [
      {
        promptUz: '“U qo‘ng‘iroq qilganda ovqat pishirayotgan edim.”',
        answer: 'I was cooking when he called.',
      },
      { promptUz: '“U uxlayotgan midimi?” (she)', answer: 'Was she sleeping?' },
      {
        promptUz: '“Biz tinglamayotgan edik.”',
        answer: "We weren't listening carefully.",
        accept: ["We weren't listening.", 'We were not listening carefully.'],
      },
      {
        promptUz: '“Ular soat 5 da o‘ynayotgan edi.”',
        answer: 'They were playing football at 5.',
        accept: ['They were playing at 5.'],
      },
    ],
    listening: [
      {
        audioText: 'I was cooking when he called',
        options: [
          'I was cooking when he called',
          'I cooked when he was calling',
          'I am cooking when he called',
          'I was cook when he called',
        ],
        answer: 0,
      },
      {
        audioText: 'Was she sleeping?',
        options: ['Was she sleeping?', 'Were she sleeping?', 'Did she sleeping?', 'Was she sleep?'],
        answer: 0,
      },
      {
        audioText: "We weren't listening carefully",
        options: [
          "We weren't listening carefully",
          "We wasn't listening carefully",
          "We didn't listening carefully",
          "We weren't listen carefully",
        ],
        answer: 0,
      },
      {
        audioText: 'While I was walking, it started to rain',
        options: [
          'While I was walking, it started to rain',
          'While I walked, it was starting to rain',
          'While I am walking, it started to rain',
          'While I was walk, it started to rain',
        ],
        answer: 0,
      },
    ],
    pronounce: [
      { text: 'was', tip: 'woz (zaif: wəz)' },
      { text: 'were', tip: 'wer' },
      { text: 'cooking', tip: 'KU-king' },
      { text: 'while', tip: 'wayl' },
      { text: 'suddenly', tip: 'SAD-n-li' },
    ],
  },
  {
    id: 'past-perfect',
    num: 14,
    level: 'ortacha',
    topic: 'zamon',
    title: 'Past Perfect',
    summary: 'O‘tmishdan oldingi o‘tmish — I had done.',
    minutes: 28,
    tip: 'had + V3. Ikki o‘tgan voqea: avvalgi = Past Perfect.',
    formula: '+ had + V3  |  − hadn’t + V3  |  ? Had + S + V3?',
    signals: ['already', 'before', 'after', 'by the time', 'just (past story)'],
    words: [
      { en: 'had', uz: 'yordamchi' },
      { en: 'before', uz: 'oldin' },
      { en: 'after', uz: 'keyin' },
      { en: 'by the time', uz: '…ga kelib' },
      { en: 'already', uz: 'allaqachon' },
      { en: 'left', uz: 'ketgan edi' },
      { en: 'eaten', uz: 'yegan edi' },
      { en: 'seen', uz: 'ko‘rgan edi' },
      { en: "hadn't", uz: 'inkor' },
      { en: 'earlier', uz: 'avvalroq' },
    ],
    phrases: [
      { en: 'I had finished before he arrived.', uz: 'U kelishidan oldin tugatgan edim.' },
      { en: 'She had never seen snow before.', uz: 'U oldin hech qor ko‘rmagan edi.' },
      { en: 'Had you eaten before the meeting?', uz: 'Uchrashuvdan oldin ovqatlanganmedingizmi?' },
      { en: "They hadn't met before 2020.", uz: 'Ular 2020 dan oldin uchrashmagan edi.' },
      { en: 'By the time we came, the film had started.', uz: 'Biz kelgunicha film boshlangan edi.' },
      { en: 'He went home after he had done his work.', uz: 'Ishini bitkazgach uyiga ketdi.' },
    ],
    quiz: [
      {
        prompt: 'To‘g‘ri:',
        options: ['I had finish', 'I had finished', 'I have finished yesterday', 'I was finished before'],
        answer: 1,
      },
      {
        prompt: 'Past Perfect vazifasi:',
        options: [
          'Hozirgi odat',
          'O‘tmishdagi undan oldingi ish',
          'Ertangi reja',
          'Hozir jarayon',
        ],
        answer: 1,
      },
      {
        prompt: 'So‘roq:',
        options: ['Had you eaten…?', 'Have you eaten before yesterday?', 'Did you had eaten…?', 'Had you ate…?'],
        answer: 0,
      },
      {
        prompt: 'by the time + Past Simple, asosiy oldin:',
        options: ['Present Simple', 'Past Perfect', 'Future Continuous', 'Present Continuous'],
        answer: 1,
      },
      {
        prompt: 'Inkor:',
        options: [
          "They hadn't met before",
          "They hadn't meet before",
          "They didn't had met",
          "They haven't met before 2010 (o‘sha hikoya uchun)",
        ],
        answer: 0,
      },
    ],
    reading: {
      title: 'Too late',
      text: 'When I arrived at the station, the train had already left. I had bought a ticket, but I had missed the announcement. By the time my friend called, I had gone home. I had never felt so tired before that day.',
      questions: [
        {
          prompt: 'Vokzalga kelganda poyezd:',
          options: ['Kutyotgan edi', 'Allaqachon ketgan edi', 'Hali kelmagan', 'Buzilgan'],
          answer: 1,
        },
        {
          prompt: 'Chipta olganmidi?',
          options: ['Yo‘q', 'Ha, olgan edi', 'Faqat ketganidan keyin', 'Do‘sti olgan'],
          answer: 1,
        },
        {
          prompt: 'Do‘st qo‘ng‘iroq qilganda:',
          options: ['Hali vokzalda', 'Uyga ketgan edi', 'Poyezdda', 'Ishda'],
          answer: 1,
        },
      ],
    },
    writing: [
      {
        promptUz: '“U kelishidan oldin tugatgan edim.”',
        answer: 'I had finished before he arrived.',
      },
      {
        promptUz: '“Biz kelgunicha film boshlangan edi.”',
        answer: 'By the time we came, the film had started.',
      },
      {
        promptUz: '“Ular 2020 dan oldin uchrashmagan edi.”',
        answer: "They hadn't met before 2020.",
        accept: ['They had not met before 2020.'],
      },
      {
        promptUz: '“Oldin qor ko‘rmagan edi.” (she)',
        answer: 'She had never seen snow before.',
      },
    ],
    listening: [
      {
        audioText: 'I had finished before he arrived',
        options: [
          'I had finished before he arrived',
          'I have finished before he arrived',
          'I finished before he had arrived (boshqa ma’no)',
          'I had finish before he arrived',
        ],
        answer: 0,
      },
      {
        audioText: 'The train had already left',
        options: [
          'The train had already left',
          'The train has already left yesterday',
          'The train had already leave',
          'The train already had leave',
        ],
        answer: 0,
      },
      {
        audioText: 'Had you eaten before the meeting?',
        options: [
          'Had you eaten before the meeting?',
          'Had you ate before the meeting?',
          'Did you had eaten before the meeting?',
          'Have you eaten before the meeting yesterday?',
        ],
        answer: 0,
      },
      {
        audioText: "They hadn't met before 2020",
        options: [
          "They hadn't met before 2020",
          "They hadn't meet before 2020",
          "They didn't had met before 2020",
          "They hasn't met before 2020",
        ],
        answer: 0,
      },
    ],
    pronounce: [
      { text: 'had', tip: 'had / həd (zaif)' },
      { text: 'already', tip: 'ol-RE-di' },
      { text: 'arrived', tip: '-ed = /d/' },
      { text: 'by the time', tip: 'by — qisqa' },
      { text: "hadn't", tip: 'HAD-nt' },
    ],
  },
  {
    id: 'past-perfect-continuous',
    num: 15,
    level: 'ilgor',
    topic: 'zamon',
    title: 'Past Perfect Continuous',
    summary: 'Oldingi o‘tmishda davom — I had been working.',
    minutes: 30,
    tip: 'had + been + V-ing. O‘tmish nuqtasidan oldin qancha davom etgani.',
    formula: '+ had + been + V-ing  |  − hadn’t + been + V-ing  |  ? Had + S + been + V-ing?',
    signals: ['for', 'since', 'before', 'until', 'all day (before past point)'],
    words: [
      { en: 'had been', uz: '…ib yurgan edi' },
      { en: 'working', uz: 'ishlab yurgan' },
      { en: 'waiting', uz: 'kutib yurgan' },
      { en: 'for hours', uz: 'soatlab' },
      { en: 'until', uz: '…gacha' },
      { en: 'before that', uz: 'undan oldin' },
      { en: 'exhausted', uz: 'holdan toygan' },
      { en: 'duration', uz: 'davomiylik' },
      { en: "hadn't been", uz: 'inkor' },
      { en: 'finally', uz: 'nihoyat' },
    ],
    phrases: [
      { en: 'I had been waiting for an hour before the bus came.', uz: 'Avtobus kelgunga qadar bir soat kutgan edim.' },
      { en: 'She had been studying all night, so she was tired.', uz: 'Tun bo‘yi o‘qigan edi, shuning uchun charchagan edi.' },
      { en: 'Had you been working there long?', uz: 'U yerda uzoq ishlab yurganmidingiz?' },
      { en: "They hadn't been living here long before they moved.", uz: 'Ko‘chishdan oldin bu yerda uzoq yashamagan edi.' },
      { en: 'He was wet because he had been walking in the rain.', uz: 'Yomg‘irda yurgani uchun ho‘l edi.' },
      { en: 'We had been talking for hours when she arrived.', uz: 'U kelganda biz soatlab gaplashib o‘tirgan edik.' },
    ],
    quiz: [
      {
        prompt: 'To‘g‘ri:',
        options: [
          'I had been work',
          'I had been working',
          'I have been working yesterday',
          'I was been working',
        ],
        answer: 1,
      },
      {
        prompt: 'Asosiy farq (Past Perfect ga):',
        options: [
          'Faqat kelajak',
          'Davomiylik / jarayon urg‘usi o‘tmishda',
          'Faqat fakt',
          'Faqat so‘roq',
        ],
        answer: 1,
      },
      {
        prompt: 'So‘roq:',
        options: [
          'Had you been working…?',
          'Have you been working yesterday…?',
          'Did you been working…?',
          'Had you been work…?',
        ],
        answer: 0,
      },
      {
        prompt: 'Sabab-natija tipik:',
        options: [
          'He was tired because he had been running',
          'He was tired because he runs',
          'He is tired because he had run tomorrow',
          'He tired because running',
        ],
        answer: 0,
      },
      {
        prompt: 'Inkor:',
        options: [
          "They hadn't been living here long",
          "They hadn't been live here long",
          "They didn't had been living",
          "They haven't been living here before 2010 story-only",
        ],
        answer: 0,
      },
    ],
    reading: {
      title: 'Before the exam',
      text: 'Before the exam started, Maria had been revising for weeks. Her eyes were red because she had been reading all night. Had she been sleeping enough? No. When the teacher entered, students had been waiting nervously for twenty minutes.',
      questions: [
        {
          prompt: 'Imtihondan oldin Mariya:',
          options: ['Dam olgan', 'Haftalab takrorlagan', 'Sayohat qilgan', 'Ishlamagan'],
          answer: 1,
        },
        {
          prompt: 'Ko‘zlari qizil — nima uchun?',
          options: ['Kasallik', 'Tun bo‘yi o‘qigan', 'Yomg‘ir', 'Kulgan'],
          answer: 1,
        },
        {
          prompt: 'O‘qituvchi kirganda talabalar:',
          options: ['Ketgan', '20 daqiqa asabiy kutgan', 'Uxlagan', 'Yozgan'],
          answer: 1,
        },
      ],
    },
    writing: [
      {
        promptUz: '“Avtobusdan oldin bir soat kutgan edim.”',
        answer: 'I had been waiting for an hour before the bus came.',
      },
      {
        promptUz: '“Yomg‘irda yurgani uchun ho‘l edi.” (he)',
        answer: 'He was wet because he had been walking in the rain.',
      },
      {
        promptUz: '“U yerda uzoq ishlab yurganmidingiz?”',
        answer: 'Had you been working there long?',
      },
      {
        promptUz: '“U kelganda soatlab gaplashgan edik.”',
        answer: 'We had been talking for hours when she arrived.',
      },
    ],
    listening: [
      {
        audioText: 'I had been waiting for an hour before the bus came',
        options: [
          'I had been waiting for an hour before the bus came',
          'I have been waiting for an hour before the bus came',
          'I had waiting for an hour before the bus came',
          'I had been wait for an hour before the bus came',
        ],
        answer: 0,
      },
      {
        audioText: 'She had been studying all night',
        options: [
          'She had been studying all night',
          'She has been studying all night yesterday',
          'She had studying all night',
          'She had been study all night',
        ],
        answer: 0,
      },
      {
        audioText: 'Had you been working there long?',
        options: [
          'Had you been working there long?',
          'Have you been working there long yesterday?',
          'Did you been working there long?',
          'Had you been work there long?',
        ],
        answer: 0,
      },
      {
        audioText: 'He was wet because he had been walking in the rain',
        options: [
          'He was wet because he had been walking in the rain',
          'He was wet because he has been walking in the rain',
          'He was wet because he had walking in the rain',
          'He is wet because he had been walking in the rain yesterday story',
        ],
        answer: 0,
      },
    ],
    pronounce: [
      { text: 'had been', tip: 'had bin' },
      { text: 'waiting', tip: 'WAY-ting' },
      { text: 'exhausted', tip: 'ig-ZOS-tid' },
      { text: 'for hours', tip: 'hours — awerz' },
      { text: 'nervously', tip: 'NER-vus-li' },
    ],
  },
  {
    id: 'future-simple',
    num: 16,
    level: 'boshlangich',
    topic: 'zamon',
    title: 'Future Simple',
    summary: 'will — bashorat, va’da, oniy qaror.',
    minutes: 24,
    tip: 'will + V1. be going to — reja/ belgi. Ikkisini farqlang.',
    formula: '+ will + V1  |  − won’t + V1  |  ? Will + S + V1?  (+ going to)',
    signals: ['tomorrow', 'soon', 'next week', 'I think', 'probably', 'I promise'],
    words: [
      { en: 'will', uz: '…adi (kelajak)' },
      { en: "won't", uz: '…maydi' },
      { en: 'going to', uz: 'niyat / belgi' },
      { en: 'tomorrow', uz: 'ertaga' },
      { en: 'soon', uz: 'tez orada' },
      { en: 'promise', uz: 'va’da' },
      { en: 'probably', uz: 'ehtimol' },
      { en: 'I think', uz: 'o‘ylayman' },
      { en: 'decide', uz: 'qaror qilmoq' },
      { en: 'prediction', uz: 'bashorat' },
    ],
    phrases: [
      { en: 'I will help you.', uz: 'Men sizga yordam beraman.' },
      { en: "It will rain tomorrow.", uz: 'Ertaga yomg‘ir yog‘adi.' },
      { en: 'Will you come with us?', uz: 'Biz bilan kelasizmi?' },
      { en: "She won't be late.", uz: 'U kechikmaydi.' },
      { en: 'I am going to study tonight.', uz: 'Bugun kechqurun o‘qimoqchiman.' },
      { en: 'Look at those clouds! It is going to rain.', uz: 'Bulutlarga qara! Yomg‘ir yog‘adi.' },
    ],
    quiz: [
      {
        prompt: 'To‘g‘ri:',
        options: ['I will helps', 'I will help', 'I will helping', 'I wills help'],
        answer: 1,
      },
      {
        prompt: 'Oniy qaror / va’da ko‘pincha:',
        options: ['will', 'Past Perfect', 'Present Perfect Continuous', 'was going'],
        answer: 0,
      },
      {
        prompt: 'Aniq reja / niyat ko‘pincha:',
        options: ['will (faqat)', 'be going to', 'had been', 'did'],
        answer: 1,
      },
      {
        prompt: 'So‘roq:',
        options: ['Will you come?', 'Do you will come?', 'Are you will come?', 'Will you coming?'],
        answer: 0,
      },
      {
        prompt: 'Inkor:',
        options: ["She won't be late", "She willn't be late", "She don't will be late", 'She not will be late'],
        answer: 0,
      },
    ],
    reading: {
      title: 'Tomorrow',
      text: 'I think it will be sunny tomorrow. I will call you in the evening. My sister is going to visit us next week. Will you join us? I won’t stay long. Look! Those dark clouds — it is going to rain soon.',
      questions: [
        {
          prompt: 'Ob-havo haqida:',
          options: ['Yomg‘ir aniq', 'Quyoshli bo‘ladi deb o‘ylayman', 'Qor', 'Shamol yo‘q'],
          answer: 1,
        },
        {
          prompt: 'Opa qachon keladi?',
          options: ['Ertaga', 'Keyingi hafta', 'Kecha', 'Hozir'],
          answer: 1,
        },
        {
          prompt: 'Qorong‘u bulutlar — nima?',
          options: ['going to rain', 'Past Simple', 'had rained', 'never rains'],
          answer: 0,
        },
      ],
    },
    writing: [
      { promptUz: '“Men sizga yordam beraman.”', answer: 'I will help you.' },
      { promptUz: '“Biz bilan kelasizmi?”', answer: 'Will you come with us?' },
      {
        promptUz: '“U kechikmaydi.” (she)',
        answer: "She won't be late.",
        accept: ['She will not be late.'],
      },
      {
        promptUz: '“Bugun kechqurun o‘qimoqchiman.”',
        answer: 'I am going to study tonight.',
        accept: ["I'm going to study tonight."],
      },
    ],
    listening: [
      {
        audioText: 'I will help you',
        options: ['I will help you', 'I will helps you', 'I will helping you', 'I would help you yesterday'],
        answer: 0,
      },
      {
        audioText: 'Will you come with us?',
        options: ['Will you come with us?', 'Do you will come with us?', 'Will you coming with us?', 'Are you will come with us?'],
        answer: 0,
      },
      {
        audioText: "She won't be late",
        options: ["She won't be late", "She willn't be late", "She don't be late", 'She not will be late'],
        answer: 0,
      },
      {
        audioText: 'I am going to study tonight',
        options: [
          'I am going to study tonight',
          'I will going to study tonight',
          'I am go to study tonight',
          'I going to study tonight',
        ],
        answer: 0,
      },
    ],
    pronounce: [
      { text: 'will', tip: 'wil' },
      { text: "won't", tip: 'wount' },
      { text: 'going to', tip: 'norasmiy: gonna' },
      { text: 'tomorrow', tip: 'to-MO-row' },
      { text: 'probably', tip: 'PROB-ab-li' },
    ],
  },
  {
    id: 'future-continuous',
    num: 17,
    level: 'ortacha',
    topic: 'zamon',
    title: 'Future Continuous',
    summary: 'Kelajakda davom — I will be working at 5.',
    minutes: 26,
    tip: 'will be + V-ing. Kelajakdagi ma’lum paytda bandlik.',
    formula: '+ will be + V-ing  |  − won’t be + V-ing  |  ? Will + S + be + V-ing?',
    signals: ['at this time tomorrow', 'at 8 pm', 'all day tomorrow', 'when you arrive'],
    words: [
      { en: 'will be', uz: '…ayotgan bo‘ladi' },
      { en: 'at this time', uz: 'shu paytda' },
      { en: 'tomorrow evening', uz: 'ertaga kechqurun' },
      { en: 'busy', uz: 'band' },
      { en: 'working', uz: 'ishlayotgan' },
      { en: 'travelling', uz: 'safarda' },
      { en: 'sleeping', uz: 'uxlayotgan' },
      { en: "won't be", uz: 'inkor' },
      { en: 'still', uz: 'hali ham' },
      { en: 'around', uz: 'taxminan' },
    ],
    phrases: [
      { en: 'This time tomorrow I will be flying to Istanbul.', uz: 'Ertaga shu paytda Istanbulga uchib ketayotgan bo‘laman.' },
      { en: 'She will be working at 6 pm.', uz: 'U soat 6 da ishlayotgan bo‘ladi.' },
      { en: 'Will you be using the car tonight?', uz: 'Bugun kechqurun mashinadan foydalanasizmi?' },
      { en: "Don't call at midnight — I will be sleeping.", uz: 'Yarim tun qo‘ng‘iroq qilmang — uxlayotgan bo‘laman.' },
      { en: "They won't be staying here long.", uz: 'Ular bu yerda uzoq qolmaydi.' },
      { en: 'When you arrive, we will be waiting.', uz: 'Siz kelganingizda biz kutayotgan bo‘lamiz.' },
    ],
    quiz: [
      {
        prompt: 'To‘g‘ri:',
        options: [
          'I will be work',
          'I will be working',
          'I will working',
          'I am will be working',
        ],
        answer: 1,
      },
      {
        prompt: 'Qachon?',
        options: [
          'Odat (har kuni)',
          'Kelajakdagi nuqtada davom etadigan ish',
          'O‘tmishdan oldingi o‘tmish',
          'Hozirgi natija',
        ],
        answer: 1,
      },
      {
        prompt: 'So‘roq:',
        options: [
          'Will you be using…?',
          'Will you using…?',
          'Do you will be using…?',
          'Are you will be using…?',
        ],
        answer: 0,
      },
      {
        prompt: 'Inkor:',
        options: [
          "I won't be sleeping",
          "I won't be sleep",
          "I willn't be sleeping",
          "I don't will be sleeping",
        ],
        answer: 0,
      },
      {
        prompt: '“This time tomorrow” bilan:',
        options: ['Past Simple', 'Future Continuous', 'Present Perfect', 'Past Perfect'],
        answer: 1,
      },
    ],
    reading: {
      title: 'This time tomorrow',
      text: 'This time tomorrow I will be sitting on a train. My parents will be preparing dinner when I arrive. Will you be working late? I won’t be checking my phone all evening — I will be resting.',
      questions: [
        {
          prompt: 'Ertaga shu paytda:',
          options: ['Uyda', 'Poyezdda', 'Ishda', 'Maktabda'],
          answer: 1,
        },
        {
          prompt: 'Men kelganda ota-ona:',
          options: ['Uxlayotgan', 'Kechki ovqat tayyorlayotgan', 'Ketgan', 'Ishda'],
          answer: 1,
        },
        {
          prompt: 'Kechqurun telefon:',
          options: ['Doim tekshiradi', 'Ko‘p tekshirmaydi — dam oladi', 'Sotadi', 'Yo‘qotadi'],
          answer: 1,
        },
      ],
    },
    writing: [
      {
        promptUz: '“Ertaga shu paytda uchib ketayotgan bo‘laman.”',
        answer: 'This time tomorrow I will be flying to Istanbul.',
        accept: ['This time tomorrow I will be flying.'],
      },
      {
        promptUz: '“Soat 6 da ishlayotgan bo‘ladi.” (she)',
        answer: 'She will be working at 6 pm.',
      },
      {
        promptUz: '“Mashinadan foydalanasizmi?” (tonight)',
        answer: 'Will you be using the car tonight?',
      },
      {
        promptUz: '“Uxlayotgan bo‘laman.” (midnight ogohlantirish)',
        answer: 'I will be sleeping.',
        accept: ["Don't call at midnight — I will be sleeping."],
      },
    ],
    listening: [
      {
        audioText: 'I will be flying to Istanbul',
        options: [
          'I will be flying to Istanbul',
          'I will flying to Istanbul',
          'I will be fly to Istanbul',
          'I am will be flying to Istanbul',
        ],
        answer: 0,
      },
      {
        audioText: 'Will you be using the car tonight?',
        options: [
          'Will you be using the car tonight?',
          'Will you using the car tonight?',
          'Do you will be using the car tonight?',
          'Will you be use the car tonight?',
        ],
        answer: 0,
      },
      {
        audioText: 'I will be sleeping',
        options: ['I will be sleeping', 'I will be sleep', 'I will sleeping', 'I would be sleeping yesterday'],
        answer: 0,
      },
      {
        audioText: 'When you arrive, we will be waiting',
        options: [
          'When you arrive, we will be waiting',
          'When you arrive, we will waiting',
          'When you will arrive, we will be waiting',
          'When you arrive, we are will be waiting',
        ],
        answer: 0,
      },
    ],
    pronounce: [
      { text: 'will be', tip: 'wil bi' },
      { text: 'flying', tip: 'FLAY-ing' },
      { text: 'tonight', tip: 'to-NIGHT' },
      { text: 'midnight', tip: 'MID-night' },
      { text: 'waiting', tip: 'WAY-ting' },
    ],
  },
  {
    id: 'future-perfect',
    num: 18,
    level: 'ilgor',
    topic: 'zamon',
    title: 'Future Perfect',
    summary: 'Kelajak nuqtasiga qadar bitgan — I will have done.',
    minutes: 28,
    tip: 'will have + V3. by tomorrow / by the time…',
    formula: '+ will have + V3  |  − won’t have + V3  |  ? Will + S + have + V3?',
    signals: ['by then', 'by tomorrow', 'by 2030', 'by the time', 'before'],
    words: [
      { en: 'will have', uz: '…gan bo‘ladi' },
      { en: 'by then', uz: 'o‘sha paytgacha' },
      { en: 'by tomorrow', uz: 'ertagacha' },
      { en: 'completed', uz: 'tugatilgan' },
      { en: 'finished', uz: 'bitgan' },
      { en: 'arrived', uz: 'yetib kelgan' },
      { en: 'deadline', uz: 'muddat' },
      { en: "won't have", uz: 'inkor' },
      { en: 'by the time', uz: '…ga kelib' },
      { en: 'already', uz: 'allaqachon' },
    ],
    phrases: [
      { en: 'By next year I will have graduated.', uz: 'Kelasi yilgacha bitirgan bo‘laman.' },
      { en: 'She will have finished by 6.', uz: 'U soat 6 gacha tugatgan bo‘ladi.' },
      { en: 'Will you have arrived by noon?', uz: 'Tushgacha yetib kelgan bo‘lasizmi?' },
      { en: "They won't have completed it by Friday.", uz: 'Juma kungacha tugatmagan bo‘lishadi.' },
      { en: 'By the time you come, I will have cooked dinner.', uz: 'Siz kelgunicha kechki ovqatni pishirgan bo‘laman.' },
      { en: 'In 2030 he will have lived here for 20 years.', uz: '2030-da u bu yerda 20 yil yashagan bo‘ladi.' },
    ],
    quiz: [
      {
        prompt: 'To‘g‘ri:',
        options: [
          'I will have finish',
          'I will have finished',
          'I will has finished',
          'I will finished',
        ],
        answer: 1,
      },
      {
        prompt: 'Asosiy signal:',
        options: ['now', 'by then / by tomorrow', 'yesterday', 'while'],
        answer: 1,
      },
      {
        prompt: 'So‘roq:',
        options: [
          'Will you have arrived…?',
          'Will you have arrive…?',
          'Do you will have arrived…?',
          'Will have you arrived…?',
        ],
        answer: 0,
      },
      {
        prompt: 'Ma’nosi:',
        options: [
          'Kelajakda hali bajarilayotgan',
          'Kelajak nuqtasiga qadar ALLAQACHON bitgan',
          'O‘tmish odat',
          'Hozirgi jarayon',
        ],
        answer: 1,
      },
      {
        prompt: 'Inkor:',
        options: [
          "They won't have completed it",
          "They won't have complete it",
          "They willn't have completed it",
          "They don't will have completed it",
        ],
        answer: 0,
      },
    ],
    reading: {
      title: 'By Friday',
      text: 'By Friday we will have finished the project. By the time the manager arrives, the team will have prepared everything. Will you have sent the email by then? I won’t have left the office before 7. In two months she will have saved enough money.',
      questions: [
        {
          prompt: 'Juma kungacha:',
          options: ['Boshlagan', 'Loyihani tugatgan', 'Dam olgan', 'Ketgan'],
          answer: 1,
        },
        {
          prompt: 'Menejer kelgunicha jamoa:',
          options: ['Uxlagan', 'Hamma narsani tayyorlagan', 'Ketgan', 'Janjallashgan'],
          answer: 1,
        },
        {
          prompt: 'Ofisdan soat 7 dan oldin chiqamanmi?',
          options: ['Ha', 'Yo‘q', 'Ertalab', 'Hech qachon ishlamayman'],
          answer: 1,
        },
      ],
    },
    writing: [
      {
        promptUz: '“Kelasi yilgacha bitirgan bo‘laman.”',
        answer: 'By next year I will have graduated.',
      },
      {
        promptUz: '“Soat 6 gacha tugatgan bo‘ladi.” (she)',
        answer: 'She will have finished by 6.',
      },
      {
        promptUz: '“Tushgacha yetib kelasizmi?”',
        answer: 'Will you have arrived by noon?',
      },
      {
        promptUz: '“Siz kelgunicha ovqat pishirgan bo‘laman.”',
        answer: 'By the time you come, I will have cooked dinner.',
      },
    ],
    listening: [
      {
        audioText: 'By next year I will have graduated',
        options: [
          'By next year I will have graduated',
          'By next year I will graduated',
          'By next year I will have graduate',
          'By next year I have will graduated',
        ],
        answer: 0,
      },
      {
        audioText: 'Will you have arrived by noon?',
        options: [
          'Will you have arrived by noon?',
          'Will you have arrive by noon?',
          'Will you arrived by noon?',
          'Do you will have arrived by noon?',
        ],
        answer: 0,
      },
      {
        audioText: "They won't have completed it by Friday",
        options: [
          "They won't have completed it by Friday",
          "They won't have complete it by Friday",
          "They won't completed it by Friday",
          "They don't have completed it by Friday",
        ],
        answer: 0,
      },
      {
        audioText: 'By the time you come, I will have cooked dinner',
        options: [
          'By the time you come, I will have cooked dinner',
          'By the time you will come, I will have cooked dinner',
          'By the time you come, I will cooked dinner',
          'By the time you come, I will have cook dinner',
        ],
        answer: 0,
      },
    ],
    pronounce: [
      { text: 'will have', tip: 'wil həv' },
      { text: 'graduated', tip: 'GRAD-u-ay-tid' },
      { text: 'by then', tip: 'by — qisqa' },
      { text: 'completed', tip: 'kom-PLI-tid' },
      { text: 'deadline', tip: 'DED-layn' },
    ],
  },
  {
    id: 'future-perfect-continuous',
    num: 19,
    level: 'ilgor',
    topic: 'zamon',
    title: 'Future Perfect Continuous',
    summary: 'Kelajak nuqtasiga qadar davom — I will have been working.',
    minutes: 30,
    tip: 'will have been + V-ing. by June — qancha vaqt davom etgani.',
    formula: '+ will have been + V-ing  |  − won’t have been + V-ing  |  ? Will + S + have been + V-ing?',
    signals: ['for', 'by then', 'by next year', 'by the time', 'How long… by…?'],
    words: [
      { en: 'will have been', uz: '…ib yurgan bo‘ladi' },
      { en: 'for ten years', uz: 'o‘n yil davomida' },
      { en: 'by June', uz: 'iyungacha' },
      { en: 'by then', uz: 'o‘sha paytgacha' },
      { en: 'working', uz: 'ishlab yurgan' },
      { en: 'studying', uz: 'o‘qib yurgan' },
      { en: 'living', uz: 'yashab yurgan' },
      { en: 'non-stop', uz: 'to‘xtovsiz' },
      { en: 'duration', uz: 'davomiylik' },
      { en: "won't have been", uz: 'inkor' },
    ],
    phrases: [
      {
        en: 'By June I will have been working here for five years.',
        uz: 'Iyungacha bu yerda 5 yil ishlab yurgan bo‘laman.',
      },
      {
        en: 'She will have been studying English for 3 years by next May.',
        uz: 'Kelasi maygacha 3 yil ingliz o‘qigan bo‘ladi.',
      },
      {
        en: 'Will you have been living here long by then?',
        uz: 'O‘sha paytgacha bu yerda uzoq yashagan bo‘lasizmi?',
      },
      {
        en: "They won't have been waiting long.",
        uz: 'Ular uzoq kutmagan bo‘lishadi.',
      },
      {
        en: 'By the time he retires, he will have been teaching for 40 years.',
        uz: 'Nafaqaga chiqquncha 40 yil dars bergan bo‘ladi.',
      },
      {
        en: 'In September we will have been building the house for a year.',
        uz: 'Sentabrda uyni 1 yil qurayotgan bo‘lamiz.',
      },
    ],
    quiz: [
      {
        prompt: 'To‘g‘ri:',
        options: [
          'I will have been work',
          'I will have been working',
          'I will have being working',
          'I will been working',
        ],
        answer: 1,
      },
      {
        prompt: 'Asosiy urg‘u:',
        options: [
          'Faqat bitgan natija',
          'Kelajak nuqtasiga qadar DAVOM etgan jarayon',
          'Hozirgi odat',
          'O‘tmish hikoya fonisiz',
        ],
        answer: 1,
      },
      {
        prompt: 'So‘roq:',
        options: [
          'Will you have been living…?',
          'Will you have being living…?',
          'Will you been living…?',
          'Do you will have been living…?',
        ],
        answer: 0,
      },
      {
        prompt: 'Future Perfect dan farqi:',
        options: [
          'Vaqt yo‘q',
          'Ko‘pincha for + davomiylik (-ing)',
          'Faqat Past',
          'Faqat Present',
        ],
        answer: 1,
      },
      {
        prompt: 'Inkor:',
        options: [
          "They won't have been waiting long",
          "They won't have been wait long",
          "They won't have being waiting long",
          "They don't will have been waiting",
        ],
        answer: 0,
      },
    ],
    reading: {
      title: 'By next decade',
      text: 'By 2030 Ava will have been running her café for ten years. By the time you read this, the team will have been developing the app for months. Will they have been working non-stop? Maybe. In December we will have been learning English together for a full year.',
      questions: [
        {
          prompt: '2030-da Ava:',
          options: [
            'Kafeni yopadi',
            '10 yil kafeni yuritgan bo‘ladi',
            'Endi boshlaydi',
            'Hech narsa qilmagan',
          ],
          answer: 1,
        },
        {
          prompt: 'Ilova jamoasi:',
          options: ['Bir kunlik ish', 'Oylardan beri ishlab kelayotgan', 'Tugatmagan va boshlamagan', 'Faqat kecha'],
          answer: 1,
        },
        {
          prompt: 'Dekabrda birga o‘rganish:',
          options: ['1 hafta', '1 yil bo‘ladi', '10 yil', 'Boshlanmagan'],
          answer: 1,
        },
      ],
    },
    writing: [
      {
        promptUz: '“Iyungacha 5 yil ishlab yurgan bo‘laman.”',
        answer: 'By June I will have been working here for five years.',
      },
      {
        promptUz: '“O‘sha paytgacha uzoq yashagan bo‘lasizmi?”',
        answer: 'Will you have been living here long by then?',
      },
      {
        promptUz: '“Ular uzoq kutmagan bo‘lishadi.”',
        answer: "They won't have been waiting long.",
        accept: ['They will not have been waiting long.'],
      },
      {
        promptUz: '“Sentabrda 1 yil qurayotgan bo‘lamiz.”',
        answer: 'In September we will have been building the house for a year.',
      },
    ],
    listening: [
      {
        audioText: 'By June I will have been working here for five years',
        options: [
          'By June I will have been working here for five years',
          'By June I will have working here for five years',
          'By June I will have been work here for five years',
          'By June I will been working here for five years',
        ],
        answer: 0,
      },
      {
        audioText: 'Will you have been living here long by then?',
        options: [
          'Will you have been living here long by then?',
          'Will you have being living here long by then?',
          'Will you been living here long by then?',
          'Will you have been live here long by then?',
        ],
        answer: 0,
      },
      {
        audioText: "They won't have been waiting long",
        options: [
          "They won't have been waiting long",
          "They won't have been wait long",
          "They won't have being waiting long",
          "They won't been waiting long",
        ],
        answer: 0,
      },
      {
        audioText: 'By the time he retires, he will have been teaching for 40 years',
        options: [
          'By the time he retires, he will have been teaching for 40 years',
          'By the time he will retire, he will have been teaching for 40 years',
          'By the time he retires, he will have teaching for 40 years',
          'By the time he retires, he will have been teach for 40 years',
        ],
        answer: 0,
      },
    ],
    pronounce: [
      { text: 'will have been', tip: 'wil həv bin — zanjir' },
      { text: 'working', tip: 'WER-king' },
      { text: 'for five years', tip: 'years — yierz' },
      { text: 'retires', tip: 'ri-TAYerz' },
      { text: 'non-stop', tip: 'non-STOP' },
    ],
  },
]
